site_name: Ontul
site_url: https://cloudcheflabs.github.io/ontul-docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: lime
  logo: images/logo/ontul-logo.png
  favicon: images/logo/ontul-logo.png


nav:
  - "Home": index.md
  - "Architecture":
      - "Ontul Architecture": architecture/architecture.md
  - "Installation":
      - "Download & Install": installation/installation.md
      - "Getting Started": intro/intro.md
  - "Features":
      - "Unified Data Engine": features/unified-engine.md
      - "Arrow-Native Execution": features/arrow-native-execution.md
      - "Connector Architecture": features/connector-architecture.md
      - "Federation Queries": features/federation.md
      - "Iceberg Integration": features/iceberg-integration.md
      - "Remote Mode": features/remote-mode.md
      - "User-Defined Functions": features/udf.md
      - "IAM": features/iam.md
      - "Encryption & KMS": features/encryption.md
      - "Geospatial Support": features/geospatial.md
      - "High Availability": features/high-availability.md
  - "Reference":
      - "REST API": reference/rest-api.md
      - "Java SDK": reference/sdk-java.md
      - "Python SDK": reference/sdk-python.md
  - "Query":
      - "Query Guide": query/guide.md
  - "Batch":
      - "Batch Guide": batch/guide.md
  - "Streaming":
      - "Streaming Guide": streaming/guide.md
  - "Community":
      - "Mailing List": community/mailing-list.md



extra:
  generator: false
  version:
    provider: mike
    default: 2.2.0


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  © <script>document.write(new Date().getFullYear())</script> Cloud Chef Labs, Inc. All rights reserved. <a href="mailto:admin@cloudchef-labs.com">admin@cloudchef-labs.com</a>